// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zojdfdoyuhcshrtwibzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvamRmZG95dWhjc2hydHdpYnp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExNDg0ODksImV4cCI6MjA3NjcyNDQ4OX0.4NNkc8B_2ZyYEsS6K9ahEc501SsDyS8GGN8iT3-g48M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});